---
title: "CV"
format: html
editor: visual
---

**Email:** [nj.mensah50\@gmail.com](mailto:nj.mensah50@gmail.com) · **LinkedIn:** [john-mensah-b46684129](https://linkedin.com/in/john-mensah-b46684129) · **GitHub:** [JohnMensah50](https://github.com/JohnMensah50)

[Download PDF version](cv.pdf){.btn .btn-outline-primary role="button"}

## Summary

- Quantitative research scientist with 6+ years of experience applying classical statistical modeling, mathematical modeling, machine learning, and time-series methods to complex, high-dimensional datasets.

- Strong programming skills in Python, R, and SQL for large-scale data analysis

- Experienced in translating ambiguous research and operational questions into well-defined analytical and modeling framework, developing and validating predictive models, and communicating complex quantitative results to technical and non-technical audiences.

- Led statistical analysis on \~8 [peer-reviewed publications](https://scholar.google.com/citations?hl=en&user=NT9u2JEAAAAJ)), requiring model validation defensible to expert reviewers and clear communication of complex methods to non-specialist audiences.

- Adaptable and committed to expanding production-oriented data science skills, including scalable ML pipelines, cloud-based analytics, and Databricks, while collaborating across disciplines to develop practical, data-driven solutions to complex real-world problems.

## Education

**Ph.D., Biological Science (major) and Statistics (minor)** — Expected 08/2026\
University of Nebraska–Lincoln, Lincoln, Nebraska, USA\
Dissertation: *Effects of Weather Variables and Insect Herbivory as Drivers of Native Plant Population Dynamics: Evidence from Long-term Demographic Monitoring*\
Advisor: Brigitte Tenhumberg, Ph.D.

**B.Sc., Forest Resources Technology** — 05/2019\
Kwame Nkrumah University of Science and Technology, Kumasi, Ghana\
Dissertation: *Comparative assessment of plant structural assemblage and composition along four riparian communities*\
Advisor: Collins Ayini Nsor, Ph.D.

## Work Experience

**Graduate Assistant** — University of Nebraska–Lincoln (01/2021 – present)

- Developed R functions for processing and cleaning modeling data
- Estimated transition probabilities of 20+ years of herbaceous plant data using GLMMs and Bayesian statistics
- Developed matrix population models (MPM) to predict plant population growth rates
- Assessed trends in climate data using ARIMA models
- Applied functional linear models (via GAMs) to evaluate time-lag effects of weather variables on plant demography
- Presented research findings to 200+ audience members across international and local conferences

**NASA DEVELOP Intern** — Langley Research Center, Hampton, Virginia, USA (06/2025 – 08/2025)

- Used JavaScript to download lake water surface temperature data from Google Earth Engine
- Applied Random Forest and XGBoost models to predict time-lag effects of air temperature on ice phenology
- Contributed to the project's [technical report](https://nasa-ext.app.box.com/s/evzrt8tvntnbwek6fx48qfnzase2g4i2/file/2001019724485)
- Presented findings to project stakeholders and NASA scientists at NASA Headquarters (DC)

**Summer Biostatistics Intern** — Streck, La Vista, Nebraska, USA (06/2023 – 08/2025)

- Developed automated R code for evaluating precision and stability of Streck's control materials for use with Sysmex XR 20/20 and Beckman Coulter DxFlex analyzers
- Led a training session for a 5-member R&D team on using R for precision/stability evaluation

**Research Assistant** — Kwame Nkrumah University of Science and Technology (08/2019 – 08/2020)

- Mentored students in research development and data analysis
- Reviewed student theses and advised on analytical approach

## Publications

### Under review

- Rachel King, Deirdre Loughnan, **John N. Mensah**, Casey O'Hara, Thilina D. Surasinghe, Titilayo T. Tajudeen, Matthew W. Austin. The promise of artificial intelligence to automate detection and mitigation of errors in large biodiversity datasets (in preparation; *Ecology and Evolution*)
- **Mensah, J. N.**, Crone, E. E., Lesica, P., & Tenhumberg, B. (2026). Time series length and statistical power to detect environmental drivers of plant demography (under review: *Ecography*). [Preprint](https://doi.org/10.22541/authorea.15006289/v1)
- **Mensah, J. N.**, Louda, S. M., Keeler, K. H., & Tenhumberg, B. (2025). Magnitude, Variation, and Impacts of Insect Foliage Herbivory on Ramet Population of *Cirsium undulatum* Over 20 Years (under review: *Ecosphere*)

### Published

- Nsor, C. A., **Mensah, J. N.**, Boadi, S., Prempeh, N. O., & Danquah, F. O. (2026). Using woody community structure as an indicator of riparian ecological integrity in Ghana's Ashanti Region. *Biodiversity*, 1–17. [doi:10.1080/14888386.2026.2690972](https://doi.org/10.1080/14888386.2026.2690972)
- **Mensah, J. N.**, Louda, S. M., Keeler, K. H., & Tenhumberg, B. (2025). Delayed Effects of Water-Limiting Conditions Influence the Ramet Demography of a Native Iterocarpic Thistle. *Ecology and Evolution*, 15(10), e72259.
- Bisselou, K. S., Hilbers, B. G., & **Mensah, J. N.** (2025). A Simple Mixed-Effects Modeling for the Precision of Automated Differential Cell Counters Using R. *Clinical and Translational Science*, 18(5), e70254.
- Nsor, C. A., Perry-Amissah, M., **Mensah, J. N.**, Boadi, S., Asigbase, M., Addae-Wireko, L., & Acolatse, R. (2025). Birds' co-occurrence is mediated by diet, habitat type, and anthropogenic disturbances in Ghana's Central Region. *Avian Research*, 16(3), 100251.
- Nsor, C. A., Dei, N. A. A., **Mensah, J. N.**, Acolatse, R., & Danquah, E. (2023). Bird community structure and habitat association in Owabi Wildlife Sanctuary, Ashanti Region (Ghana). *Wildlife Research*.
- Nsor, C. A., Acolatse, R., **Mensah, J. N.**, Oppong, S. K., Dompreh, D., & Addai-Wireko, L. (2022). Structural assemblages of plant species in the Owabi Ramsar Wetland in the Ashanti Region of Ghana. *African Journal of Aquatic Science*, 47(1), 100–114.
- Nsor, C. A., **Mensah, J. N.**, & Agumenu, V. (2021). Riparian vegetation dynamics in protected and unprotected areas, Kumawu District—Ashanti Region (Ghana). *Tropical Ecology*, 62(3), 329–346.
- Nsor, C. A., **Mensah, J. N.**, Barnes, V. R., & Akomatey, P. K. (2021). Anthropogenic drivers of plant species coexistence in selected riparian systems, Kumawu district, Ashanti region (Ghana). *Journal of Freshwater Ecology*, 36(1), 323–344.

## Presentations

- Mensah, J. N., Crone, E. E., Lesica, P., Tyre, A. J., & Tenhumberg, B. (Aug 2025). *How long to monitor plant demography to detect signal of weather variables.* ESA Annual Conference, Baltimore, MD. Oral presentation (Population Ecology section)
- Mensah, J. N., Svata, L., Keeler, K., & Tenhumberg, B. (Aug 2024). *Contribution of weather variables to the demographic dynamics of the thistle species, Cirsium undulatum.* ESA Annual Conference, Long Beach, CA. Oral presentation (Statistics section)
- Mensah, J. N., Svata, L., Keeler, K., & Tenhumberg, B. (Mar 2024). *Exploring the effect of weather variables on temporal dynamics of Cirsium undulatum demography in two Prairie Grasslands.* EEB Seminar
- Mensah, J. N., Svata, L., Keeler, K., & Tenhumberg, B. (Mar 2023). *Effect of plant size and insect herbivory on Cirsium undulatum (Wavyleaf Thistle).* EEB Seminar
- Mensah, J. N., Crone, E. E., Lesica, P., Tyre, A. J., & Tenhumberg, B. (Aug 2022). *Past events determine current performance: Prolonged dormancy and weather.* ESA/CSEE Annual Conference, Montreal, Canada. Poster
- Mensah, J. N., Crone, E. E., Lesica, P., Tyre, A. J., & Tenhumberg, B. (Dec 2022). *Past events determine current performance: Prolonged dormancy and weather.* British Ecological Society Conference, Scotland. Oral presentation
- Mensah, J. N., Crone, E. E., Lesica, P., Tyre, A. J., & Tenhumberg, B. (Oct 2021). *The role of variation in weather variables in shaping plant life histories: whole plant dormancy and flowering.* EEB Seminar

## Awards

- 2026 Dr. John F. Davidson Prize for outstanding graduate student in Botany or Plant Systems, School of Biological Sciences, UNL
- \$1,000 funding to attend ESIIL 2025 Innovation Summit, University of Colorado Boulder (Sept 2025)
- \$1,550, Myrle M. Burk Botany Memorial Fund
- Scholarship, 3rd Annual Environmental Data Science Summit, NCEAS (Santa Barbara, CA, Feb 2025)
- Graduate Student Travel Award (\$500; sponsored by Warren and Edith Day)
- Carl W. Gugler Memorial Award, 2nd Place Poster Presentation, BIOGSA Symposium, UNL
- Dr. John F. Davidson Memorial Fund (\$1,445; May 2024)
- Funding to attend short course, *Forecasting for Decision-Making: An Epidemiological and Ecological Perspective*, Canadian Ecological Forecasting Initiative, Fields Institute, Toronto (Jul 2023)
- Dr. John F. Davidson Memorial Fund (\$990; May 2023)
- Blair Paxton Udale Fund for Life Sciences (\$1,000; May 2022)
- National Science Foundation Scholarship Award (Aug 2020 – Jul 2021), Tenhumberg Lab, UNL

## Short Courses & Certifications

- Using Google Earth Engine in Ecological Studies — PRstats (Dr. Oliver Hooker)
- ARSET Certificate, Invasive Species Monitoring with Remote Sensing — NASA (Oct 2024)
- 6.86x Machine Learning with Python: From Linear Models to Deep Learning — MITx (Jul 2024)
- 6.419x Data Analysis: Statistical Modeling and Computation in Applications — MITx (Jul 2024)
- 6.431x Probability: The Science of Uncertainty and Data — MITx (Apr 2024)
- 18.6501x Fundamentals of Statistics — MITx (May 2024)
- Spatial Data Science: The New Frontier in Analytics — Esri Training (Oct 2023)
- Forecasting for Decision-Making: An Epidemiological and Ecological Perspective — Canadian Ecological Forecasting Initiative, Fields Institute (Jul 2023)
- Data for Better Lives: A New Social Contract — World Bank Group (edX)
- The Inclusive STEM Teaching Project — Boston University (edX, Aug 2021)
- Responsible Conduct of Research & Biomedical RCR — CITI Program (May 2021)

## Skills

:::: grid
::: g-col-6
-  ArcGIS Pro
- Time series analysis
- Machine (Deep) learning
- Multivariate analysis
- Technical communication & data storytelling
- R & Python programming
- Data management and visualization
- Version control systems (e.g., Git)
- Cross-Functional Collaboration
- Team-leading, Mentoring, & Knowledge sharing
:::
::::

## Volunteer Activities

- Graduate student representative, Davidson-Fuller Presidential Chair for Plant Sciences search committee, SBS, UNL
- Graduate student representative, SBS Community Conversation committee
- Reviewer, *Journal of Freshwater Ecology*
- Copy editor and reviewer, *Journal of Emerging Investigators*
- Climate and Justice Team, St. Paul United Methodist Church, Lincoln, NE — funding proposals for tree planting; carbon footprint reduction guidelines

## References

Available upon request.
